#!/usr/bin/env node
// Fetch the latest release tag from MagnetonIO/copied-app and write it into
// lib/version-generated.ts so the website's CTA / download URLs always point
// at the most recent .pkg without anyone editing source per release.
//
// Wired as `prebuild` in package.json — runs before `next build` on every
// Vercel deploy. A GitHub release-published webhook (configured on the
// copied-app repo) hits a Vercel deploy hook so the rebuild fires
// automatically the moment a new release ships.
//
// Failure mode: if GitHub is unreachable, rate-limited, or returns garbage,
// we leave version-generated.ts untouched so the build still ships with the
// previously-known good version.

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const REPO = "MagnetonIO/copied-app";
const GENERATED_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "lib",
  "version-generated.ts"
);

async function fetchLatestTag() {
  const url = `https://api.github.com/repos/${REPO}/releases/latest`;
  const headers = {
    Accept: "application/vnd.github+json",
    "User-Agent": "getcopied-app-build"
  };
  // GITHUB_TOKEN bumps the unauthenticated 60/h rate limit to 5000/h. Vercel
  // exposes one automatically when the integration is connected; locally the
  // script falls back to unauthenticated, which is plenty for human dev runs.
  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  }
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`GitHub responded ${res.status}`);
  const data = await res.json();
  if (typeof data.tag_name !== "string") throw new Error("missing tag_name");
  return data.tag_name.replace(/^v/, "");
}

function readCurrentTag() {
  if (!existsSync(GENERATED_PATH)) return null;
  const m = readFileSync(GENERATED_PATH, "utf8").match(
    /LATEST_RELEASE_TAG\s*=\s*"([^"]+)"/
  );
  return m ? m[1] : null;
}

const current = readCurrentTag();
let next;
try {
  next = await fetchLatestTag();
} catch (err) {
  console.warn(
    `[sync-version] GitHub fetch failed (${err.message}); keeping existing tag ${current ?? "<none>"}`
  );
  process.exit(0);
}

if (next === current) {
  console.log(`[sync-version] tag unchanged: ${next}`);
  process.exit(0);
}

const banner = "// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n";
const body = `export const LATEST_RELEASE_TAG = "${next}";\n`;
writeFileSync(GENERATED_PATH, banner + body, "utf8");
console.log(`[sync-version] tag bumped: ${current ?? "<none>"} → ${next}`);
